# Generated by Django 4.1.4 on 2022-12-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('geners', models.CharField(choices=[('action', 'Action'), ('thriller', 'Thriller'), ('drama', 'Drama'), ('horror', 'Horror'), ('comedy', 'Comedy'), ('romance', 'Romance'), ('history', 'History'), ('adventure', 'Adventure'), ('sci-fi', 'Sci-Fi'), ('fantasy', 'Fantasy')], max_length=50)),
                ('director', models.CharField(choices=[('steven spielberg', 'Steven Spielberg'), ('martin scorsese', 'Martin Scorsese'), ('quentin tarantino', 'Quentin Tarantino'), ('francis ford coppola', 'Francis Ford Coppola'), ('marko nabersnik', 'Marko Naberšnik'), ('nicolas winding refn', 'Nicolas Winding Refn'), ('oliver hirschbiegel', 'Oliver Hirschbiegel'), ('stanley kubrick', 'Stanley Kubrick')], max_length=50)),
                ('language', models.CharField(choices=[('en', 'English'), ('sl', 'Slovene'), ('ge', 'German'), ('dk', 'Danish')], max_length=50)),
                ('star', models.CharField(choices=[('harrison ford', 'Harrison Ford'), ('sean connery', 'Sean Connery'), ('morgan freeman', 'Morgan Freeman'), ('kurt russel', 'Kurt Russel'), ('adam sandler', 'Adam Sandler'), ('jack nicholson', 'Jack Nicholson'), ('vlado novak', 'Vlado Novak'), ('mads mikkelsen', 'Mads Mikkelsen'), ('brad pitt', 'Brad Pitt'), ('matt damon', 'Matt Damon'), ('ben affleck', 'Ben Affleck'), ('mark wahlberg', 'Mark Wahlberg'), ('sandra bullock', 'Sandra Bullock'), ('meryl streep', 'Meryl Streep'), ('bruno ganz', 'Bruno Ganz')], max_length=50)),
                ('rating', models.FloatField(max_length=4)),
            ],
        ),
    ]
