# Generated by Django 4.1.4 on 2022-12-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='franchise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='hollywood',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='true_story',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
